apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.netbox.oss.netboxlabs.com/
    chart: netbox
    targetRevision: 5.0.0-beta.50 # Specificeer de gewenste versie
    helm:
      valueFiles:
        - namespace.yaml
        - values.yaml
        - ingress.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: netbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

