apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/netbox-community/netbox-chart/netbox
    chart: netbox
    helm:
      valueFiles:
        - namespace.yaml
        - values.yaml
        - ingress.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: netbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

