apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://charts.netbox.oss.netboxlabs.com/
    chart: netbox
    targetRevision: 5.0.0-beta.50 # Specificeer de gewenste versie
    helm:
      valueFiles:
        - $values/netbox-argocd/namespace.yaml 
        - $values/netbox-argocd/values.yaml
        - $values/netbox-argocd/ingress.yaml
  - repoURL: https://github.com/bkampsnl/k8s.git 
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: netbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

